'use strict';
function setVoucherType(t){ state.currentType=t; qsa('.type-btn').forEach(b=>b.classList.toggle('selected',b.dataset.type===t)); qsa('.credit-fields').forEach(e=>e.classList.toggle('hidden',t!=='credit')); qsa('.debit-fields').forEach(e=>e.classList.toggle('hidden',t!=='debit')); qsa('.onaccount-fields').forEach(e=>e.classList.toggle('hidden',t!=='onaccount')); }
function resetVoucherForm(){ $('voucherForm')?.reset(); if($('editId'))$('editId').value=''; if($('vDate'))$('vDate').value=todayISO(); setVoucherType('debit'); if($('formTitle'))$('formTitle').textContent='Create Voucher'; }
async function maybeAddHead(name,type){ name=String(name||'').trim().replace(/\s+/g,' '); if(!name)return ''; if(state.heads.some(h=>norm(h.name)===norm(name)))return name; if(confirm(`"${name}" is not in the dropdown. Do you want to add it and sync for all users?`)){ const j=await api('addHead',{name,type}); state.heads=mergeHeads(j.heads||[]); populateHeads(); toast('Account head added and synced.','ok'); } return name; }
async function saveVoucher(ev){
  ev.preventDefault(); const type=state.currentType; const headField=type==='credit'?'creditAccount':type==='onaccount'?'onAccountHead':'debitHead'; const paidField=type==='onaccount'?'onPaidTo':'paidTo';
  const head=await maybeAddHead($(headField)?.value,type); const amount=amountInt($('amount')?.value); if(!head||!amount||!$('towards')?.value.trim())return toast('Fill Head, Towards and Amount.','err');
  const v={ id:$('editId')?.value||undefined, type, date:$('vDate').value, college:$('vCollege').value, head, ac_name:$('creditAccount')?.value||'', received_from:$('receivedFrom')?.value||'', paid_to:type==='credit'?'':($(paidField)?.value||''), towards:$('towards').value, amount, amt_words:numberToWords(amount), mode:$('mode').value, cheque:$('cheque').value, prep_by:$('preparedBy').value, checked_by:$('checkedBy').value, remarks:$('remarks').value };
  await api('saveVoucher',{voucher:v}); toast('Voucher saved.','ok'); resetVoucherForm(); await loadAll(true); showPage(isAdmin()?'allVouchers':'myVouchers');
}
function applyFilters(){ state.filters={from:$('fFrom').value,to:$('fTo').value,type:$('fType').value,head:$('fHead').value,mode:$('fMode').value,user:$('fUser').value,search:$('fSearch').value.trim(),view:$('fView').value}; renderAllVouchers(); }
function clearFilters(){ ['fFrom','fTo','fType','fMode','fUser','fSearch'].forEach(id=>{if($(id))$(id).value='';}); if($('fHead'))$('fHead').value='__all_heads__'; if($('fView'))$('fView').value='table'; state.filters={from:'',to:'',type:'',head:'__all_heads__',mode:'',user:'',search:'',view:'table'}; renderAllVouchers(); }
function editVoucher(id){ if(!isAdmin())return toast('Only admin can edit.','err'); const v=state.vouchers.find(x=>Number(x.id)===Number(id)); if(!v)return; showPage('create'); setVoucherType(v.type); $('editId').value=v.id; $('formTitle').textContent='Edit Voucher'; $('vDate').value=v.date; $('vCollege').value=v.college||'smg'; $('creditAccount').value=v.ac_name||v.head||''; $('receivedFrom').value=v.received_from||''; $('debitHead').value=v.head||''; $('paidTo').value=v.paid_to||''; $('onAccountHead').value=v.head||''; $('onPaidTo').value=v.paid_to||''; $('towards').value=v.towards||''; $('amount').value=amountInt(v.amount); $('amountWords').value=numberToWords(v.amount); $('mode').value=v.mode||'Cash'; $('cheque').value=v.cheque||''; $('preparedBy').value=v.prep_by||''; $('checkedBy').value=v.checked_by||''; $('remarks').value=v.remarks||''; }
async function deleteVoucher(id){ if(!isAdmin())return; if(!confirm('Delete this voucher? It will be soft-deleted with audit log.'))return; await api('deleteVoucher',{id}); toast('Voucher deleted.','ok'); await loadAll(true); }
function openPrint(id){ const v=state.vouchers.find(x=>Number(x.id)===Number(id)); if(!v)return; $('printArea').innerHTML=printHtml(v); $('printModal').classList.remove('hidden'); }
function printHtml(v){ const title=(TYPE_LABEL[v.type]||'Voucher')+' Voucher'; return `<div class="voucher-print"><div class="voucher-head"><h2>ST. MARY'S VOUCHER SYSTEM</h2><div>${safe(title.toUpperCase())}</div></div><div class="voucher-meta"><div><b>Date:</b> ${safe(dmy(v.date))}</div><div><b>No:</b> ${safe(v.voucher_no||v.id)}</div></div><div class="print-row"><b>Head</b><span>${safe(v.head)}</span></div><div class="print-row"><b>Party</b><span>${safe(v.paid_to||v.received_from||v.ac_name||'—')}</span></div><div class="print-row"><b>Towards</b><span>${safe(v.towards)}</span></div><div class="print-row"><b>Amount</b><span><b>${money(v.amount)}</b></span></div><div class="print-row"><b>In Words</b><span>${safe(v.amt_words||numberToWords(v.amount))}</span></div><div class="print-row"><b>Mode / Ref</b><span>${safe(v.mode||'')} ${safe(v.cheque||'')}</span></div><div class="sign-row"><div>Prepared By<br><br>____________</div><div>Receiver / Depositor<br><br>____________</div></div></div>`; }
function doPrint(){ const html=$('printArea').innerHTML; const w=window.open('', '_blank'); w.document.write(`<!doctype html><html><head><title>Voucher</title><link rel="stylesheet" href="style.css"></head><body class="print-document">${html}<script>setTimeout(()=>print(),300)<\/script></body></html>`); w.document.close(); }
function exportRows(rows,name){ if(typeof XLSX==='undefined')return toast('Excel library not loaded.','err'); const data=rows.map(v=>({Date:dmy(v.date),'Voucher No':v.voucher_no||v.id,Type:TYPE_LABEL[v.type],Party:v.paid_to||v.received_from||v.ac_name||'',Head:v.head,Towards:v.towards,Mode:v.mode,Amount:amountInt(v.amount),'Created By':v.created_by})); const ws=XLSX.utils.json_to_sheet(data); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,'Vouchers'); XLSX.writeFile(wb,name+'.xlsx'); }
function exportFiltered(){ exportRows(filteredVouchers(),'Filtered_Vouchers_'+todayISO()); }
function exportMine(){ exportRows(state.vouchers.filter(v=>v.created_by===state.user.username),'My_Vouchers_'+todayISO()); }
function exportLedger(){ const rows=filteredVouchers(), out=[]; Object.entries(groupByHead(rows)).forEach(([head,items])=>{ out.push({Date:'Head: '+head}); items.forEach(v=>out.push({Date:dmy(v.date),Type:TYPE_LABEL[v.type],Party:v.paid_to||v.received_from||v.ac_name||'',Towards:v.towards,Amount:amountInt(v.amount)})); out.push({Date:'Head Total',Amount:items.reduce((s,v)=>s+amountInt(v.amount),0)}); }); const ws=XLSX.utils.json_to_sheet(out); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,'Ledger'); XLSX.writeFile(wb,'Ledger_Report_'+todayISO()+'.xlsx'); }
function exportCashBook(){ const rows=filteredVouchers(), receipts=rows.filter(v=>v.type==='credit'), payments=rows.filter(v=>v.type!=='credit'), n=Math.max(receipts.length,payments.length), aoa=[['Receipts','','','Payments','',''],['Particulars','Head','Amount','Particulars','Head','Amount']]; for(let i=0;i<n;i++){const r=receipts[i],p=payments[i]; aoa.push([r?(r.received_from||r.ac_name||'')+' t/w '+r.towards:'',r?.head||'',r?amountInt(r.amount):'',p?(p.paid_to||'')+' t/w '+p.towards:'',p?.head||'',p?amountInt(p.amount):'']);} aoa.push(['Total','',receipts.reduce((s,v)=>s+amountInt(v.amount),0),'Total','',payments.reduce((s,v)=>s+amountInt(v.amount),0)]); const ws=XLSX.utils.aoa_to_sheet(aoa); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,'Cash Book'); XLSX.writeFile(wb,'CashBook_'+todayISO()+'.xlsx'); }
async function createUser(ev){ ev.preventDefault(); await api('createUser',{username:$('newUsername').value,password:$('newPassword').value,role:$('newRole').value,college:$('newCollege').value}); toast('User created.','ok'); $('userForm').reset(); const j=await api('listUsers'); state.users=j.users||[]; renderUsers(); }
async function toggleUser(username,status){ if(!confirm(`Set ${username} as ${status}?`))return; await api('setUserStatus',{username,status}); const j=await api('listUsers'); state.users=j.users||[]; renderUsers(); }
async function resetUserPassword(username){ const password=prompt('Enter new password for '+username); if(!password)return; await api('resetPassword',{username,password}); toast('Password reset.','ok'); }
function bindEvents(){ $('loginForm')?.addEventListener('submit',async e=>{e.preventDefault();try{await login($('loginUsername').value.trim(),$('loginPassword').value);}catch(err){$('loginError').hidden=false;$('loginError').textContent=err.message;}}); $('setupForm')?.addEventListener('submit',async e=>{e.preventDefault();try{await setupAdmin($('setupKey').value,$('setupPassword').value);}catch(err){toast(err.message,'err');}}); $('showSetupBtn')?.addEventListener('click',()=>{$('loginForm').classList.add('hidden');$('setupForm').classList.remove('hidden');}); $('backLoginBtn')?.addEventListener('click',()=>{$('setupForm').classList.add('hidden');$('loginForm').classList.remove('hidden');}); qsa('.nav').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page))); qsa('.type-btn').forEach(b=>b.addEventListener('click',()=>setVoucherType(b.dataset.type))); $('amount')?.addEventListener('input',()=>{$('amountWords').value=numberToWords($('amount').value);}); $('voucherForm')?.addEventListener('submit',saveVoucher); $('resetVoucherBtn')?.addEventListener('click',resetVoucherForm); $('applyFilterBtn')?.addEventListener('click',applyFilters); $('clearFilterBtn')?.addEventListener('click',clearFilters); $('downloadExcelBtn')?.addEventListener('click',exportFiltered); $('downloadLedgerBtn')?.addEventListener('click',exportLedger); $('downloadCashBookBtn')?.addEventListener('click',exportCashBook); $('downloadMyExcelBtn')?.addEventListener('click',exportMine); $('closePrintBtn')?.addEventListener('click',()=>$('printModal').classList.add('hidden')); $('printBtn')?.addEventListener('click',doPrint); $('userForm')?.addEventListener('submit',createUser); $('reloadAuditBtn')?.addEventListener('click',loadAudit); $('refreshBtn')?.addEventListener('click',()=>loadAll(true)); $('logoutBtn')?.addEventListener('click',logout); }
window.openPrint=openPrint; window.editVoucher=editVoucher; window.deleteVoucher=deleteVoucher; window.toggleUser=toggleUser; window.resetUserPassword=resetUserPassword;
window.initVoucherApp = async function(){
  bindEvents();
  if(state.token){ try{ const j=await api('validateSession'); state.user=j.user; await enterApp(); } catch{ localStorage.removeItem('smv_token'); } }
};
