(function(){
  'use strict';
  const API_URL='/api/public/voucher/x';
  const USER_ALIAS={admin:'admin1',admin1:'admin1',user2:'admin2',admin2:'admin2',user3:'admin3',admin3:'admin3'};
  function token(){return localStorage.getItem('smv_token')||'';}
  function setToken(t){if(t)localStorage.setItem('smv_token',t);else localStorage.removeItem('smv_token');}
  function uiUserCode(u){const name=String((u&&u.username)||u||'').toLowerCase();if((u&&u.role)==='admin'||name==='admin'||name==='admin1')return'admin1';if(USER_ALIAS[name])return USER_ALIAS[name];if(name.indexOf('3')>-1)return'admin3';return'admin2';}
  function candidates(n){n=String(n||'').trim().toLowerCase();if(n==='admin1')return['admin1','admin'];if(n==='admin2')return['admin2','user2'];if(n==='admin3')return['admin3','user3'];return[n];}
  function dmy(s){s=String(s||'');if(/^\d{4}-\d{2}-\d{2}$/.test(s)){const p=s.split('-');return p[2]+'-'+p[1]+'-'+p[0];}return s;}
  function iso(s){s=String(s||'');if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const p=s.split('-');return p.length===3?p[2]+'-'+p[1]+'-'+p[0]:s;}
  async function api(action,payload){const body=Object.assign({},payload||{},{action:action,token:token()});const r=await fetch(API_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok||j.error)throw new Error(j.error||('HTTP '+r.status));return j;}
  window._api=api;
  function toOld(v){const o={id:Number(v.id||0),voucherNo:v.voucher_no||'',date:dmy(v.date),dateISO:iso(v.date),type:v.type||'debit',college:v.college||CURRENT_COLLEGE||'smg',head:v.head||'',acName:v.ac_name||'',receivedFrom:v.received_from||'',paidTo:v.paid_to||'',towards:v.towards||'',amount:Number(v.amount||0),amtWords:v.amt_words||'',mode:v.mode||'Cash',cheque:v.cheque||'',prepBy:v.prep_by||'',checkedBy:v.checked_by||'',remarks:v.remarks||'',createdBy:uiUserCode(v.created_by||''),createdAt:v.created_at||'',_u:v.updated_at||v.created_at||''};o.party=o.paidTo||o.receivedFrom||o.acName||'';return o;}
  function toApi(v){return{id:v.id&&String(v.id).length<12?Number(v.id):0,college:CURRENT_COLLEGE||v.college||'smg',type:v.type||CVT||'debit',date:iso(v.dateISO||v.date),head:v.head||'',ac_name:v.acName||'',received_from:v.receivedFrom||'',paid_to:v.paidTo||'',towards:v.towards||'',amount:Math.round(Number(v.amount||0)),amt_words:v.amtWords||'',mode:v.mode||'Cash',cheque:v.cheque||'',prep_by:v.prepBy||'',checked_by:v.checkedBy||'',remarks:v.remarks||''};}
  async function syncHeads(){try{const j=await api('listHeads',{college:CURRENT_COLLEGE||'smg'});(j.heads||[]).forEach(h=>{const n=h&&h.name;if(n&&!HEADS.some(x=>String(x).toLowerCase()===String(n).toLowerCase()))HEADS.push(n);});if(typeof populateHeads==='function')populateHeads();if(typeof populateMyHeads==='function')populateMyHeads();const dl=document.getElementById('DL_HEADS');if(dl)dl.innerHTML=HEADS.map(h=>'<option value="'+String(h).replace(/"/g,'&quot;')+'"></option>').join('');}catch(e){}}
  window._refreshCredentialsCache=async function(college){try{const j=await api('validateSession',{});const code=uiUserCode(j.user),m={};m[code]='1';_CRED_CACHE[college||CURRENT_COLLEGE||'smg']=m;return m;}catch(e){try{sessionStorage.clear();}catch(_e){}setToken('');const cp=document.getElementById('CP');if(cp)cp.style.display='flex';const app=document.getElementById('APP');if(app)app.style.display='none';return{};}};
  window.doLogin=async function(){const typed=document.getElementById('LU').value.trim().toLowerCase();const pw=document.getElementById('LP').value;const le=document.getElementById('LE');if(le)le.style.display='none';if(!typed||!pw){if(le){le.textContent='Enter username and password.';le.style.display='block';}return;}let ok=null,last=null;for(const u of candidates(typed)){try{ok=await api('login',{username:u,password:pw});break;}catch(e){last=e;}}if(!ok){if(le){le.textContent=(last&&last.message)||'Invalid credentials';le.style.display='block';}return;}setToken(ok.token);CU=uiUserCode(ok.user);CURRENT_COLLEGE=(ok.user&&ok.user.college)||CURRENT_COLLEGE||'smg';HOME_COLLEGE=CURRENT_COLLEGE;document.getElementById('LS').style.display='none';document.getElementById('CP').style.display='none';document.getElementById('APP').style.display='block';document.getElementById('UB').textContent=(ADMIN_ROLES[CU]||{label:CU}).label;updateCollegeSwitchPill();await syncHeads();await _loadVouchersFromCloud();setupRole();initApp();_updateXLPill();const cs=document.getElementById('f_college');if(cs){cs.value=CURRENT_COLLEGE;cs.disabled=true;}try{sessionStorage.setItem('smv_sess_user',CU);sessionStorage.setItem('smv_sess_college',CURRENT_COLLEGE);sessionStorage.setItem('smv_sess_home',CURRENT_COLLEGE);}catch(e){}_startLiveSync();};
  window.doSignup=function(){const se=document.getElementById('SE');if(se){se.textContent='Live version: users are created by admin only.';se.style.display='block';}};
  window.doResetPassword=function(){const re=document.getElementById('RE');if(re){re.textContent='Live version: password reset is handled by admin.';re.style.display='block';}};
  window.logout=function(){CU=null;HOME_COLLEGE=null;setToken('');_stopLiveSync();try{sessionStorage.clear();}catch(e){}document.getElementById('APP').style.display='none';backToPicker();};
  window._loadVouchersFromCloud=async function(){try{const j=await api('listVouchers',{college:CURRENT_COLLEGE||'smg'});VS=(j.vouchers||[]).map(toOld);}catch(e){console.error(e);}};
  async function maybeHead(v){const n=String(v.head||'').trim();if(!n||HEADS.some(h=>String(h).toLowerCase()===n.toLowerCase()))return;if(confirm('"'+n+'" is not in the dropdown. Do you want to add it and sync for all users?')){try{await api('addHead',{name:n,type:v.type||'common',college:CURRENT_COLLEGE||v.college||'smg'});HEADS.push(n);await syncHeads();}catch(e){_toast('Head sync failed: '+e.message,'err');}}}
  window._saveVoucherToCloud=async function(v){await maybeHead(v);const p=toApi(v);const j=await api('saveVoucher',{college:p.college,voucher:p});if(j&&j.id){v.id=j.id;v.voucherNo=j.voucher_no||v.voucherNo||'';}v.createdBy=CU;v._u=new Date().toISOString();return j;};
  window._deleteVoucherFromCloud=async function(id){try{await api('deleteVoucher',{id:id});}catch(e){_toast('Delete failed: '+e.message,'err');}};
  window._startLiveSync=function(){_stopLiveSync();_LIVE_SIG=_vsSignature();_LIVE_TIMER=setInterval(async()=>{if(!CU||!token()||document.hidden)return;try{const j=await api('listVouchers',{college:CURRENT_COLLEGE||'smg'});const next=(j.vouchers||[]).map(toOld);const sig=next.length+'|'+next.map(v=>v.id+':'+(v._u||v.dateISO||'')).join(',');if(sig!==_LIVE_SIG){VS=next;_LIVE_SIG=sig;try{renderVT();renderDash();renderMyDash();renderMyVT();}catch(e){}}}catch(e){}},5000);};
  document.addEventListener('DOMContentLoaded',function(){const lu=document.getElementById('LU');if(lu)lu.placeholder='admin / user2 / user3';});
})();
